### ISSUE TITLE
cSprite::SetFrame will not work

### ISSUE THREAD

**Issue by kukukuan2023** [AaronLiddiment/LEDSprites#4]
Not matter what you set, the frame is set to the last one.

This line should be corrected.
https://github.com/AaronLiddiment/LEDSprites/blob/4b7fc6ba028138d9b0690b935c49883fb749965b/LEDSprites.cpp#L311

**Comment by AaronLiddiment** [comment]
Quite right, stupid mistake, should be 'min'
